version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: pebbles

  pebbles:
    build: .
    ports:
      - "8081:8081"
    environment:
      MONGO_URI: mongodb://mongodb:27017/pebbles
      PORT: 8081
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongodb_data: