version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: pebbles

  pebbles:
    build: .
    ports:
      - "8081:8081"
    environment:
      MONGO_URI: mongodb://mongodb:27017/pebbles
      PORT: 8081
      # SQS Configuration (disabled by default)
      SQS_ENABLED: "false"
      SQS_QUEUE_URL: ${SQS_QUEUE_URL:-}
      AWS_REGION: ${AWS_REGION:-us-east-1}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      # Kafka Configuration (disabled by default)
      KAFKA_ENABLED: "false"
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-}
      KAFKA_TOPIC_NAME: ${KAFKA_TOPIC_NAME:-progress-updates}
      KAFKA_GROUP_ID: ${KAFKA_GROUP_ID:-pebbles-consumer}
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongodb_data: